"""empty message

Revision ID: 686fceba301d
Revises: 
Create Date: 2021-03-29 14:51:18.658717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '686fceba301d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hashtag', sa.String(), nullable=True),
    sa.Column('writer', sa.Integer(), nullable=True),
    sa.Column('caption', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('img_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crawler')
    # ### end Alembic commands ###
