"""empty message

Revision ID: 94ee4747481b
Revises: e1c4aa44249c
Create Date: 2021-03-30 13:25:17.530765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94ee4747481b'
down_revision = 'e1c4aa44249c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crawler', 'writer')
    op.drop_column('crawler', 'caption')
    op.drop_column('crawler', 'tags')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crawler', sa.Column('tags', sa.VARCHAR(), nullable=True))
    op.add_column('crawler', sa.Column('caption', sa.VARCHAR(), nullable=True))
    op.add_column('crawler', sa.Column('writer', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
